title: Krista Lyn White
description: >- # this means to ignore newlines until "baseurl:"
  Krista Lyn White's books, work experience, notes, and contact information.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://kristalynwhite.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kristalynwhite
github_username:  klwdesigns

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
